# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    ENV["FASTLANE_USER"] = "nut.developers@icloud.com"
    ENV["FASTLANE_PASSWORD"] = "nut.develop3rS*!"
  end

  lane :beta do
    #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
    #git_url("https://github.com/memolopezmx/tutorial-certificate.git")
    #match(git_basic_authorization: base64encoded(username("memolopezmx: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"), type: "development", app_identifier: ["mx.com.actions-test"])
    match(git_basic_authorization: Base64.strict_encode64("memolopezmx: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"), type: "development")
    #gym(scheme: "actions-test", workspace: "actions-test.xcworkspace")
  end
end


