# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    ENV['MATCH_GIT_BASIC_AUTHORIZATION'] = 'bWVtb2xvcGV6bXg6Z2hwX09WbG96WEZMMG50MTZuSVlreE5DZ3RPWWtuZUREWTB5VXcyYg=='
    ENV['ISSUER_ID'] = '69a6de8e-df7f-47e3-e053-5b8c7c11a4d1'
  end

  lane :beta do
    #api_key = app_store_connect_api_key(
    #  key_id: "TX3Y3W5B82",
    #  issuer_id: "69a6de8e-df7f-47e3-e053-5b8c7c11a4d1",
    #  key_filepath: "./AuthKey_TX3Y3W5B82.p8"
    #)
    #match(api_key: api_key, type: "development")
    match(type: "development")
    gym(scheme: "actions-test", workspace: "actions-test.xcworkspace", export_method: "development", output_directory: "./ipas", output_name: "test1.ipa")
  end

  lane :beta2 do 
    
  end
end
