# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end

lane :beta do
  #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
  #git_url("https://github.com/memolopezmx/tutorial-certificate.git")
  match(git_basic_authorization: Base64.strict_encode64("memolopezmx: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"), type: "development", app_identifier: ["mx.com.actions-test"])
  gym(scheme: "actions-test", workspace: "actions-test.xcworkspace")
end


