name: Linterna

on: [push]

jobs:
  main:
    runs-on: testrunner
    steps:
    - name: Check out the code
      uses: actions/checkout@v2
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}