name: merge_develop

on: [push, workflow_dispatch]

env:
  MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

jobs:
  build:
    runs-on: testrunner
    steps:
    - uses: actions/checkout@v2

    - name: Install Bundler
      run: gem install bundler   

    - name: Bundle
      run: rm .Gemfile.lock && bundle update && bundle install

    - name: Build
      run: bundle exec fastlane beta