name: merge_develop

on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Bundle
      run: bundle install

    - name: Build
      run: bundle exec fastlane beta