name: merge_develop

on: [push, workflow_dispatch]

env:
  MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

jobs:
  build:
    runs-on: testrunner
    steps:
    - uses: actions/checkout@v2

    - name: Install Bundler
      run: fastlane -v