name: merge_develop

on: [push, workflow_dispatch]

env:
  MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

jobs:
  build:
    runs-on: testrunner
    steps:
    - uses: actions/checkout@v2

    - name: Ruby
      run: rvm use 2.6.6

    - name: Install Bundler
      run: gem install bundler

    - name: Install Bundler
      run: bundle update          

    - name: Bundle
      run: bundle install

    - name: Build
      run: bundle exec fastlane beta