name: merge_develop

on: push

env:
  MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: fastlane beta

